"""repr dept canged

Revision ID: 257563504eff
Revises: 765da0d09bde
Create Date: 2021-05-28 15:26:24.935920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '257563504eff'
down_revision = '765da0d09bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depts_empls')
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['id_dept'], ['id_dept'])
    op.create_table('depts_empls',
    sa.Column('id_dept', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id_empl', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_dept'], ['department.id_dept'], name='depts_empls_ibfk_1'),
    sa.ForeignKeyConstraint(['id_empl'], ['employee.id_empl'], name='depts_empls_ibfk_2'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
