"""repr dept canged

Revision ID: 765da0d09bde
Revises: c76180f8f552
Create Date: 2021-05-28 15:10:00.025094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '765da0d09bde'
down_revision = 'c76180f8f552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('id_dept', sa.Integer(), nullable=True))
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['id_dept'], ['id_dept'])
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_ibfk_1', 'employee', 'department', ['department_id'], ['id_dept'])
    op.drop_column('employee', 'id_dept')
    # ### end Alembic commands ###
