"""birth -> birthday

Revision ID: c76180f8f552
Revises: ca2bd605e227
Create Date: 2021-05-28 12:16:03.360134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c76180f8f552'
down_revision = 'ca2bd605e227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.drop_column('employee', 'birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('birth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('employee', 'birthday')
    # ### end Alembic commands ###
