"""foreign key added, datetime

Revision ID: ca2bd605e227
Revises: 5e41dd0446de
Create Date: 2021-05-27 18:37:52.431038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca2bd605e227'
down_revision = '5e41dd0446de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id_dept'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.drop_column('employee', 'department_id')
    # ### end Alembic commands ###
