"""test

Revision ID: 6e278e6caf8b
Revises: 6e3c24515bca
Create Date: 2021-05-25 15:41:17.723596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e278e6caf8b'
down_revision = '6e3c24515bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('eid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('birth', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('salary', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.PrimaryKeyConstraint('eid'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('book',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('author', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=False),
    sa.Column('cost', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('published', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
