"""Empoyee table added

Revision ID: 6e3c24515bca
Revises: fa224542ccd8
Create Date: 2021-04-30 16:10:39.481268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3c24515bca'
down_revision = 'fa224542ccd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('birth', sa.Integer(), nullable=True),
    sa.Column('salary', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    # ### end Alembic commands ###
