"""genre deleted, cost and published added

Revision ID: fa224542ccd8
Revises: 
Create Date: 2021-04-30 15:19:24.935340

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa224542ccd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('cost', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('published', sa.Integer(), nullable=True))
    op.drop_column('book', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre', mysql.VARCHAR(collation='utf8_unicode_ci', length=250), nullable=True))
    op.drop_column('book', 'published')
    op.drop_column('book', 'cost')
    # ### end Alembic commands ###
